# -*- coding: utf-8 -*-
"""AluraStore humber.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YK2TB5pzBU0L9X2B4L-lfHu0TSA9bgIs

### Importación de datos
"""

import pandas as pd

url = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_1%20.csv"
url2 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_2.csv"
url3 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_3.csv"
url4 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_4.csv"

tienda = pd.read_csv(url)
tienda2 = pd.read_csv(url2)
tienda3 = pd.read_csv(url3)
tienda4 = pd.read_csv(url4)

tienda.head()

"""#1. Análisis de facturación


"""

tienda.tail()
tienda["Precio"].sum()
print(f"La facturacion total de la tienda 1 es de {tienda["Precio"].sum()} pesos")

tienda2["Precio"].sum()

tienda3["Precio"].sum()

tienda4["Precio"].sum()

sumaPrecios = tienda["Precio"].sum() + tienda2["Precio"].sum() + tienda3["Precio"].sum() + tienda4["Precio"].sum()
print(f"La suma total de ventas de todas las tiendas es de {sumaPrecios} pesos")

print(f"Las ventas de la tienda 1 son {tienda["Precio"].sum()} pesos, \n la tienda 2 ha vendido un total de {tienda2["Precio"].sum()} pesos, \n la tienda 3 ha vendido un total de {tienda3["Precio"].sum()} pesos y \n la tienda 4 ha vendido un total de {tienda4["Precio"].sum()} pesos")

"""**La tienda con más ventas es la número 1, seguido de la 2, después la 3 y finalmente la 4**

# 2. Ventas por categoría
"""

print(f"Los productos más vendidos en esta tienda son los siguientes:")
tienda.groupby("Categoría del Producto").size().sort_values(ascending=False)

print(f"Los productos más vendidos en esta tienda son los siguientes:")
tienda2.groupby("Categoría del Producto").size().sort_values(ascending=False)

print(f"Los productos más vendidos en esta tienda son los siguientes:")
tienda3.groupby("Categoría del Producto").size().sort_values(ascending=False)

print(f"Los productos más vendidos en esta tienda son los siguientes:")
tienda4.groupby("Categoría del Producto").size().sort_values(ascending=False)

todoslosdf = [tienda, tienda2, tienda3, tienda4]
totalventas = pd.concat(todoslosdf)
totalventas

totalventas["Categoría del Producto"].isin(["Muebles", "Electrónicos"])
filtropopulares = totalventas["Categoría del Producto"].isin(["Muebles", "Electrónicos"])

ventaspopulares = totalventas[filtropopulares]
ventaspopulares

"""**Los artículos más vendidos en todas las tiendas son Electrónicos y Muebles**

# 3. Calificación promedio de la tienda
"""

tienda["Calificación"].mean()

tienda2['Calificación'].mean()

tienda3['Calificación'].mean()

tienda4['Calificación'].mean()

"""**La tienda con el mejor puntaje es la número 3, seguido de la 2, posteriormente la 4 y al final la número 1.**

# 4. Productos más y menos vendidos
"""

tienda.groupby("Producto").size().sort_values(ascending=False)

print(f"En la tienda 1, los 5 más vendidos fueron Armarios, Televisiones, Microondas, Secadoras y Mesas. \n Mientras que los menos vendidos fueron Mochilas, Panderetas, Ollas, Ceulares y Audífonos")

tienda2.groupby("Producto").size().sort_values(ascending=False)

print(f"En la tienda 2, los productos más vendidos fueron Cursos de programación, Microondas, Baterías, Panderetas, y Guitarras \n Mientras que los menos vendidos fueron Audífonos, Sillones, Impresoras, Mesas y Juegos de mesa")

tienda3.groupby("Producto").size().sort_values(ascending=False)

print(f"En esta tienda fueron Bancas, Comedores, Camas, Ollas y Mesas \n Y los menos vendidos fueron Guitarras, Mochilas, Microondas, Vasos y Bloques")

tienda4.groupby("Producto").size().sort_values(ascending=False)

print(f"Aquí fueron Camas, Cubertería, Colchones, Dashboards y Coches de radiocontrol \n Mientras que los otros fueron Cursos de ciencia de datos, Refrigeradores, Guitarras, Armarios y Guitarras eléctricas")

"""# 5. Envío promedio por tienda"""

tienda["Costo de envío"].mean()

tienda2["Costo de envío"].mean()

tienda3["Costo de envío"].mean()

tienda4["Costo de envío"].mean()

"""**La tienda con el costo promedio de envío más alto es la número 1, seguido de la tienda 2, luego la tienda 3 y por último, el costo de envío más chico es de la tienda número 4**

# 6. Gráfico de barras: Calificación promedio por tienda
"""

import matplotlib.pyplot as plt
data = {
    'Tienda': ['Tienda 1', 'Tienda 2', 'Tienda 3', 'Tienda 4'],
    'Calificación Promedio': [3.977, 4.037, 4.048, 3.996]
}
df_calificaciones = pd.DataFrame(data)

plt.figure(figsize=(8, 5))
plt.bar(
    df_calificaciones['Tienda'],
    df_calificaciones['Calificación Promedio'],
    color=['#4C72B0', '#55A868', '#C44E52', '#8172B2']
)
plt.xlabel("Tienda")
plt.ylabel("Calificación Promedio")
plt.title("Gráfico 1: Calificación Promedio por Tienda")
plt.ylim(3.95, 4.06)
plt.grid(axis='y', linestyle='--')
plt.savefig("calificaciones_promedio_tiendas.png")
plt.close()

from IPython.display import Image
Image(filename='calificaciones_promedio_tiendas.png')

"""# 7. Gráfico de pastel: Distribución de categorías"""

distribucion_categorias = totalventas.groupby('Categoría del Producto').size().sort_values(ascending=False)
distribucion_categorias

plt.figure(figsize=(10, 10))
plt.pie(
    distribucion_categorias.values,
    labels=distribucion_categorias.index,
    autopct='%1.1f%%',
    startangle=90,
    wedgeprops={'edgecolor': 'black'}
)
plt.title("Gráfico 2: Distribución de Ventas por Categoría")
plt.axis('equal')
plt.savefig("distribucion_categorias_circular.png")
plt.close()

from IPython.display import Image
Image(filename="distribucion_categorias_circular.png")

"""# 8. Gráfico de dispersión: Relación entre costo de envío y precio del producto"""

plt.figure(figsize=(10, 6))
plt.scatter(totalventas['Precio'], totalventas['Costo de envío'], alpha=0.3)
plt.title("Gráfico 3: Relación entre Precio del Producto y Costo de Envío")
plt.xlabel("Precio del Producto")
plt.ylabel("Costo de Envío")
plt.grid(True, linestyle='--', alpha=0.6)
plt.savefig("precio_vs_envio_dispersion.png")
plt.close()

from IPython.display import Image
Image(filename="precio_vs_envio_dispersion.png")

"""# 9. Informe final

1. Introducción:

En la actualidad, la conductas de consumo hacen que las condiciones de los mercados  al mismo tiempo que en la industria tecnológica se han vuelto, volátiles, inciertos, complejos y ambiguos, por lo que no resulta extraño, sino hasta necesario, considerar las posibilidades de la diversificación.

En este sentido, la constante en algunas industrias ha sido esta, máxime que empresas de gran calado han necesitado de "no poner los huevos en la misma canasta"; por ejemplo, si bien es ampliamente conocida en el sector de comida rápida, McDonald's también es una gran inmobiliaria. Por otra parte, de una forma más sutil, empresas como Apple han cambiado su modelo de negocio hacia los servicios, complementados con la venta de hardware.

Ante esta situación, la incertidumbre es la máxima de las inquietudes del stakeholder que ha solicitado los servicios de análisis de datos provistos en el presente informe, quien ha manifestado la necesidad de vender una de sus tiendas para invertir en un nuevo negocio. Sin embargo, ante la incertidumbre, la mejor forma de mitigar riesgos y tomar la mejor decisión es a través del análisis e interpretación de datos (conocido en inglés como data-driven decision making), por lo que el propósito de este informe versa sobre la interpretación y explicación de la mejor decisión en beneficio del tomador de decisiones.

2. Metodología:
El análisis de datos requiere de un método que por lo general se compone por lo siguiente:
a) Preguntar
b) Preparar
c) Procesar
d) Analizar
e) Compartir
f) Actuar
En este caso, las fase de pregunta incluyó la mayor cantidad de información relevante posible, como los tipos de productos vendidos y su categoría, la cantidad, precio, valor de envío, ubicación de la tienda, vendedores, calificación, método de pago, entre otros. La preparación de datos se trató sobre el proceso de limpieza de datos, es decir, formatos correctos, valores revisados, etc.
Por lo que la labor principal se centró en procesar, analizar y compartir los datos para que el stakeholder pueda actuar.

A la luz de los reusltados obtenidos a través de los datos, es posible proporcionar un informe que facilite la toma de decisión del Señor Juan, con relación a la venta de una de las cuatro tiendas que actualmente posee.
Primeramente, durante el análisis de facturación, se constató que la tienda con más ventas es la número 1 con una facturación de 1,150,880,400.0, seguido de la tienda número 2 con 1,116,343,500.0, después la número 3 con un total de 1,098,019,600.0 y finalmente la tienda número 4 con 1,038,375,700.0, donde la diferencia entre la primera y la última tienda es de 112,504,700 pesos colombianos.

Por otra parte, los artículos más vendidos en todas las tiendas son electrónicos y muebles, lo que deja de manifiesto el interés principal del consumidor. Sin embargo, al momento de medir la calificación promedio de los clientes a cada tienda, se constata un hecho diametralmente opuesto al primero manifestado, sinedo que la tienda mejor valorada es la número 3, mientras que la peor calificada es la número 1, no obstante es importante tomar en cuenta que la tienda con la menor calificación promedio tiene un 3.97 y la tienda con la calificación más alta tiene un 4.04, como se aprecia en el gráfico 1, lo que puede sugerir un poco o nulo significado para la toma de decisiones, situación sobre la que se ahondará más adelante.

Dentro de la exploración de los productos más y menos vendidos (no confundir con categoría), en la tienda 1, los 5 más vendidos fueron Armarios, Televisiones, Microondas, Secadoras y Mesas, mientras que los menos vendidos fueron Mochilas, Panderetas, Ollas, Ceulares y Audífonos; en la tienda 2 los más vendidos fueron Cursos de programación, Microondas, Baterías, Panderetas, y Guitarras, al tiempo que los menos vendidos fueron Audífonos, Sillones, Impresoras, Mesas y Juegos de mesa; para el caso de la tienda 3 se vendieron más Bancas, Comedores, Camas, Ollas y Mesas
Y menos Guitarras, Mochilas, Microondas, Vasos y Bloques; por último en la tienda 4 los más vendidos fueron Camas, Cubertería, Colchones, Dashboards y Coches de radiocontrol, cuando los menos vendidos fueron Cursos de ciencia de datos, Refrigeradores, Guitarras, Armarios y Guitarras eléctricas.

Por último, en el análisis de los costos de envío (pagados por los clientes) se ha observado una correlación significativa de tipo positivo fuerte entre el costo del envío y el valor del artículo, como se aprecia en el gráfico 3, dando como resultados en el coeficiente de Pearson un valor de 0.99, en Spearman un 0.96 y en Kendall 0.88, sugiriendo que los clientes pagan más por envío por artículos más caros, lo que puede impactar positivamente sobre los márgenes de ganancia, en este caso, la tienda número 4 es la que tiene un valor de envío más bajo con relación a las demás, siendo la número 1 la que tiene el valor más alto.

3. Decisión:
En razón de lo anteriormente expuesto, la tienda que se sugiere vender al Señor Juan es la número 4, principalmente por su baja facturación y costos de envío más bajos, dato que apunta a márgenes de ganancia más pequeños, además de que su participación en el portafolio de empesas del Señor Juan no indica un impacto sustancial. El único punto que la ubica en una mejor situación es la calificación promedio, siendo la tercera mejor calificada, especialmente comparándose contra la tienda 1; sin embargo, como se explicó anteriormente, la correlación entre valor de artículo y costo de envío es de muy alto significado entre las dos variables. Por otra parte, el aumento de la calificación de la tienda 1 puede abordarse desde la perspectiva orgaizacional a través del estudio y mejoramiento del clima laboral, además del trato hacia los clientes.
"""

